about:
  home: https://github.com/jamesgregson/easy_image_io
  license: MIT (https://opensource.org/licenses/MIT)
  summary: "Straightforward 16 bit image I/O"

package:
  name: easy_image_io
  version: 0.1

source:
  url:  https://github.com/jamesgregson/easy_image_io/archive/master.zip

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - libpng
    - libtiff
  run:
    - numpy

build:
  number: 1

test:
  imports:
    - easy_image_io
